version: '3.1'

volumes:
  dbdata:

services:
  db:
    image: mysql:5.7
    command:  >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD_ROOT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql